// All order items from the PDF organized by category
export const DEFAULT_ORDER_ITEMS = [
  // أكواب وأطباق
  { category: "أكواب وأطباق", name: "صحون فرايز صغير - 6x6x3 BLACK" },
  { category: "أكواب وأطباق", name: "صحون حجم عادي - 9x6x3 BLACK" },
  { category: "أكواب وأطباق", name: "صحون سلطة كبير - 9x9x2.8 BLACK" },
  { category: "أكواب وأطباق", name: "صحون عروس - 9x9x2.8 3 Compt BLACK" },
  { category: "أكواب وأطباق", name: "أكواب للشوربة 6oz" },
  { category: "أكواب وأطباق", name: "صحن المشوي دجاجة واحدة - Aluminium Half" },
  { category: "أكواب وأطباق", name: "غطاء صحن المشوي دجاجة واحدة" },
  { category: "أكواب وأطباق", name: "صحن المشوي فامیلي - Aluminium Full" },
  { category: "أكواب وأطباق", name: "غطاء صحن المشوي فامیلي" },
  { category: "أكواب وأطباق", name: "صحن المشوي نصف دجاجة - Half Size Medium" },
  { category: "أكواب وأطباق", name: "غطاء صحن المشوي نصف دجاجة" },
  { category: "أكواب وأطباق", name: "كرتونة وجبة الواردة المفردة" },
  // علب الصوص
  { category: "علب الصوص", name: "علب التوم الصغيرة 1 أونص" },
  { category: "علب الصوص", name: "غطاء علب التوم الصغيرة 1 أونص" },
  { category: "علب الصوص", name: "علب التوم الصغيرة 2 أونص" },
  { category: "علب الصوص", name: "غطاء علب التوم الصغيرة 2 أونص" },
  { category: "علب الصوص", name: "علب توم الفامیلي 8oz" },
  { category: "علب الصوص", name: "غطاء علب توم الفامیلي" },
  { category: "علب الصوص", name: "علب صوص المندي 4 أونص" },
  { category: "علب الصوص", name: "غطاء علب صوص المندي 4 أونص" },
  // أدوات المائدة
  { category: "أدوات المائدة", name: "معالق مغلفة 1000 ct" },
  { category: "أدوات المائدة", name: "شوك سودة 1000 ct" },
  { category: "أدوات المائدة", name: "شلمونات 8 inch" },
  { category: "أدوات المائدة", name: "ورق لف السندوش 14x14" },
  { category: "أدوات المائدة", name: "ورق 14x14 للصواني" },
  { category: "أدوات المائدة", name: "لوينا شفاف مقاس 18x2000" },
  { category: "أدوات المائدة", name: "ورق زبدة 14x14" },
  { category: "أدوات المائدة", name: "كرار قصدير للتغليف 18 inch" },
  { category: "أدوات المائدة", name: "بكانة محارم - نابكن" },
  { category: "أدوات المائدة", name: "محارم بيضاء لمسح البسطة" },
  { category: "أدوات المائدة", name: "أكياس لوينا كبيرة 1000 ct" },
  { category: "أدوات المائدة", name: "ورق طابعة الكاش" },
  // مواد غذائية
  { category: "مواد غذائية", name: "بطاطا فرايز - Cavendish 3/8" },
  { category: "مواد غذائية", name: "زيت نقي 16 Lt" },
  { category: "مواد غذائية", name: "طحين كيس 20KG" },
  { category: "مواد غذائية", name: "سكر 10x2kg" },
  { category: "مواد غذائية", name: "توم مقشر طازج 18LB" },
  { category: "مواد غذائية", name: "حمص حبة 50lb" },
  { category: "مواد غذائية", name: "ملح 20kg" },
  { category: "مواد غذائية", name: "سيتريك أسيد 5lb" },
  { category: "مواد غذائية", name: "خل أبيض 4x4Lt" },
  { category: "مواد غذائية", name: "خل مرا 6x4Lt" },
  { category: "مواد غذائية", name: "سكر آيسنج" },
  { category: "مواد غذائية", name: "كزبرة طازجة" },
  { category: "مواد غذائية", name: "سطل طحينة 18KG" },
  { category: "مواد غذائية", name: "فلفل أبيض" },
  { category: "مواد غذائية", name: "سمسم 10LB" },
  { category: "مواد غذائية", name: "بابريكا مدخنة 9x445g" },
  { category: "مواد غذائية", name: "بابريكا اسبانية 9x430g" },
  { category: "مواد غذائية", name: "نشا ذرة 50lb" },
  { category: "مواد غذائية", name: "خبز همبرغر 8ct" },
  { category: "مواد غذائية", name: "كعك مطحون - Bread Crumbs 10lb" },
  { category: "مواد غذائية", name: "خردل أصفر 16x400g" },
  { category: "مواد غذائية", name: "صوص ببي للهمبرغر - Worcester 4Lt" },
  { category: "مواد غذائية", name: "جبنة الهمبرغر - Cheddar Slices" },
  { category: "مواد غذائية", name: "خيار رائحة للغر 2x4Lt" },
  { category: "مواد غذائية", name: "ماجي دجاج 24x21g" },
  { category: "مواد غذائية", name: "بودر البوتين - Knorr Cream Base 1.5kg" },
  { category: "مواد غذائية", name: "صبغة لون أصفر 20x400g" },
  { category: "مواد غذائية", name: "صبغة لون برتقالي 20x400g" },
  { category: "مواد غذائية", name: "صبغة لون أحمر فاتح 20x400g" },
  { category: "مواد غذائية", name: "ظروف صوص هوت Wings" },
  { category: "مواد غذائية", name: "ظروف شبكة Ketchup" },
  // منتجات الألبان
  { category: "منتجات الألبان", name: "موزاريلا Silani 5x2kg" },
  { category: "منتجات الألبان", name: "جبنة للازرالي صوص Parmesan 2x2.5kg" },
  { category: "منتجات الألبان", name: "بيض 15x12ct" },
  { category: "منتجات الألبان", name: "علب حمص للمسحة 6x1100Z" },
  { category: "منتجات الألبان", name: "ذرة للسلطة 12x141ml" },
  { category: "منتجات الألبان", name: "مايونيز كبير 15.4Lt" },
  { category: "منتجات الألبان", name: "عيران Ayran 24x473ml" },
  { category: "منتجات الألبان", name: "زبدة غير مملة - Unsalted Butter" },
  { category: "منتجات الألبان", name: "جبنة البوتين 2KG" },
  { category: "منتجات الألبان", name: "سطل بيبي Gravy 4x1.5kg" },
  // مواد التنظيف
  { category: "مواد التنظيف", name: "سائل الجلي الأزرق DAWN 4x3.78Lt" },
  { category: "مواد التنظيف", name: "منظف غريل وفراير 4x4Lt" },
  { category: "مواد التنظيف", name: "كلور Clorox 3.357Lt" },
  { category: "مواد التنظيف", name: "لايزول منظف 4x949ml" },
  { category: "مواد التنظيف", name: "معطر أرض Pine-sol 3x4.24Lt" },
  { category: "مواد التنظيف", name: "هيرنت للشعر 100ct" },
  { category: "مواد التنظيف", name: "أكياس زبالة صغيرة 26x36 200ct" },
  { category: "مواد التنظيف", name: "أكياس زبالة كبيرة 42x48 125ct" },
  // مشروبات
  { category: "مشروبات", name: "ماء 24 قنينة 500ml" },
  { category: "مشروبات", name: "كولا Coca Cola 24x355ml" },
  { category: "مشروبات", name: "كولا ديتا Diet Coke 24x355ml" },
  { category: "مشروبات", name: "كولا زيرو Coke Zero 24x355ml" },
  { category: "مشروبات", name: "كولا جينجر Canada Dry 24x355ml" },
  { category: "مشروبات", name: "كولا سبرايت Sprite 24x355ml" },
  { category: "مشروبات", name: "بيبسي ديتا Pepsi Diet 24x355ml" },
  { category: "مشروبات", name: "بيبسي Pepsi Original 24x355ml" },
  { category: "مشروبات", name: "بيبسي كراش Crush Orange 24x355ml" },
  // كول سلو
  { category: "خضار وسلطات", name: "قرنبيط للكول سلو 5lb" },
]
