export const DEFAULT_ORDER_ITEMS = [
  // أكواب وأطباق - Containers & Plates
  { no: "1", category: "Containers & Plates - أكواب وأطباق", code: "TOC588", uom: "250CT", nameEn: "Value Plus - MFPP - Clamshell Container - 6x6x3 - BLACK", nameAr: "صحون فرايز صغير" },
  { no: "2", category: "Containers & Plates - أكواب وأطباق", code: "TOC338", uom: "2*100CT", nameEn: "Value Plus - MFPP CONTAINER 9*6*3 - NG-018 - BLACK", nameAr: "صحون حجم عادي" },
  { no: "3", category: "Containers & Plates - أكواب وأطباق", code: "TOC085", uom: "150CT", nameEn: "Value Plus - MFPP - Clamshell Container - 9x9x2.8\" - 1 Compt - BLACK", nameAr: "صحون سلطة كبير" },
  { no: "4", category: "Containers & Plates - أكواب وأطباق", code: "TOC087", uom: "150CT", nameEn: "MFPP - Clamshell Container - 9x9x2.8\" - 3 Compt - BLACK", nameAr: "صحون عروس" },
  { no: "15", category: "Containers & Plates - أكواب وأطباق", code: "CUP027-G205", uom: "1000CT", nameEn: "6oz Cups for soups", nameAr: "أكواب للشوربة" },
  { no: "16", category: "Containers & Plates - أكواب وأطباق", code: "4*40", uom: "4*40", nameEn: "Eco-Craze - #8 Natural Container - EFHPN4", nameAr: "كرتونة وجبة الواردة المفردة" },
  // صحون المشوي - Grill Trays
  { no: "17", category: "Grill Trays - صحون المشوي", code: "ALU026", uom: "100CT", nameEn: "Lids for Aluminium Tray - Half Size", nameAr: "غطاء صحن المشوي دجاجة واحدة" },
  { no: "18", category: "Grill Trays - صحون المشوي", code: "ALU015", uom: "100CT", nameEn: "Aluminium Tray - Half Size DEEP", nameAr: "صحن المشوي دجاجة واحدة" },
  { no: "19", category: "Grill Trays - صحون المشوي", code: "", uom: "30CT", nameEn: "Lids for Aluminium Tray - Full Size", nameAr: "غطاء صحن المشوي فامیلي" },
  { no: "20", category: "Grill Trays - صحون المشوي", code: "ALU005", uom: "50CT", nameEn: "Aluminium Tray - Full Size Medium", nameAr: "صحن المشوي فامیلي" },
  { no: "", category: "Grill Trays - صحون المشوي", code: "ALU104", uom: "100CT", nameEn: "Rhino-Foil - Half Size Lid - Aluminium Steam Pan - Heavy", nameAr: "غطاء صحن المشوي نصف دجاجة" },
  { no: "", category: "Grill Trays - صحون المشوي", code: "ALU102", uom: "100CT", nameEn: "Rhino-Foil - Half Size Medium - Aluminium Steam Pan", nameAr: "صحن المشوي نصف دجاجة" },
  // علب الصوص - Sauce Cups
  { no: "6", category: "Sauce Cups - علب الصوص", code: "TOC038 PC1Dt", uom: "20x125CT", nameEn: "Dart - Portion Cups - 1 oz - PC1Dt", nameAr: "علب التوم الصغيرة 1 أونص" },
  { no: "7", category: "Sauce Cups - علب الصوص", code: "TOC039 PC1LA", uom: "20x125CT", nameEn: "Dispose - Lids for Portion Cups - 1 oz - PC1LA", nameAr: "غطاء علب التوم الصغيرة 1 أونص" },
  { no: "8", category: "Sauce Cups - علب الصوص", code: "TOC042 PC2Dt", uom: "20x125CT", nameEn: "Dart - Portion Cups - 2 oz - PC2Dt", nameAr: "علب التوم الصغيرة 2 أونص" },
  { no: "9", category: "Sauce Cups - علب الصوص", code: "TOC043 PC2LA", uom: "20x125CT", nameEn: "Dispose - Lids for Portion Cups - 2 oz - PC2LA", nameAr: "غطاء علب التوم الصغيرة 2 أونص" },
  { no: "10", category: "Sauce Cups - علب الصوص", code: "TOC118-D201", uom: "10x50CT", nameEn: "Hoffman - Deli Container - Clear - 8oz - HT08-99A", nameAr: "علب توم الفامیلي" },
  { no: "11", category: "Sauce Cups - علب الصوص", code: "TOC124-D217", uom: "10x50CT", nameEn: "Hoffman - Clear Deli Lid - Fits all Sizes", nameAr: "غطاء علب توم الفامیلي" },
  { no: "12", category: "Sauce Cups - علب الصوص", code: "TOC393", uom: "10x250CT", nameEn: "Dart - Portion Cups - 3.25 oz - P325N", nameAr: "علب صوص المندي 4 أونص" },
  { no: "13", category: "Sauce Cups - علب الصوص", code: "TOC806", uom: "10x250CT", nameEn: "Dispose - Lids for Portion Cups - 3.25 oz - PC400L", nameAr: "غطاء علب صوص المندي 4 أونص" },
  // أدوات المائدة - Cutlery & Wraps
  { no: "5", category: "Cutlery & Wraps - أدوات المائدة", code: "CUT124", uom: "1000CT", nameEn: "Wrapped Soup Spoon", nameAr: "معالق مغلفة" },
  { no: "21", category: "Cutlery & Wraps - أدوات المائدة", code: "CUT007-C920B", uom: "1000CT", nameEn: "Dispose - Fork - Ind. Wrapped - Heavy - Black", nameAr: "شوك سودة" },
  { no: "22", category: "Cutlery & Wraps - أدوات المائدة", code: "STR049 ST8", uom: "9x400CT", nameEn: "8\" Ind. Wrapped Milkshake Straws", nameAr: "شلمونات" },
  { no: "23", category: "Cutlery & Wraps - أدوات المائدة", code: "WRP011 A129D", uom: "1000CT", nameEn: "Dispose - Insulated Foil Wrap - 14\"x14\"", nameAr: "ورق لف السندوش 14x14" },
  { no: "24", category: "Cutlery & Wraps - أدوات المائدة", code: "WRP073", uom: "1000CT", nameEn: "Checkered Sheets - Black - 14\"x14\"", nameAr: "ورق 14x14 للصواني" },
  { no: "25", category: "Cutlery & Wraps - أدوات المائدة", code: "WRP020 F113", uom: "1CT", nameEn: "Crystal - Food Wrap Film - 18\"x2000'", nameAr: "لوينا شفاف كركر" },
  { no: "26", category: "Cutlery & Wraps - أدوات المائدة", code: "", uom: "1000CT", nameEn: "Parchment Paper 14\"x14\"", nameAr: "ورق زبدة" },
  { no: "27", category: "Cutlery & Wraps - أدوات المائدة", code: "WRP080", uom: "1CT", nameEn: "Can Foil - 18\" Aluminum Foil 100M", nameAr: "كرار قصدير للتغليف" },
  { no: "14", category: "Cutlery & Wraps - أدوات المائدة", code: "BAG015 S5LW", uom: "1000CT", nameEn: "Plastic Bags - Low Density - White - S5", nameAr: "أكياس لوينا كبيرة" },
  { no: "28", category: "Cutlery & Wraps - أدوات المائدة", code: "NAP007-N102A", uom: "12x500CT", nameEn: "Cardinal - Luncheon Napkins - 1/4 Fold", nameAr: "محارم نابكين" },
  { no: "30", category: "Cutlery & Wraps - أدوات المائدة", code: "PAP118", uom: "4*6", nameEn: "Sponge - 2 Ply Ultra Paper Towel Rolls - 72 sheets", nameAr: "محارم بيضاء لمسح البسطة" },
  { no: "32", category: "Cutlery & Wraps - أدوات المائدة", code: "", uom: "50 ROLLS", nameEn: "POS Roll Papers 3 1/8\"x3\"", nameAr: "ورق طابعة الكاش" },
  // مواد غذائية - Food Ingredients
  { no: "40", category: "Food Ingredients - مواد غذائية", code: "FRO158-FroFr04", uom: "6x4.5 LB", nameEn: "Cavendish - French Fries - Clear Coat - 3/8", nameAr: "بطاطا فرايز" },
  { no: "41", category: "Food Ingredients - مواد غذائية", code: "OIL087", uom: "16 LT", nameEn: "Pure Drop/Messina - Vegetable Oil", nameAr: "زيت نقي" },
  { no: "49", category: "Food Ingredients - مواد غذائية", code: "FLR006", uom: "20 KG", nameEn: "Bakers Hood - Flour - All Purpose", nameAr: "طحين كيس" },
  { no: "", category: "Food Ingredients - مواد غذائية", code: "SUG001", uom: "10x2 KG", nameEn: "Redpath - Sugar", nameAr: "سكر سكيس" },
  { no: "58", category: "Food Ingredients - مواد غذائية", code: "PR0084", uom: "18 LB", nameEn: "Fresh Garlic - Peeled", nameAr: "توم مقشر طازج" },
  { no: "59", category: "Food Ingredients - مواد غذائية", code: "LEN079-Daalc350", uom: "50 LB", nameEn: "Chick Peas - White - 9mm", nameAr: "حمص" },
  { no: "60", category: "Food Ingredients - مواد غذائية", code: "SPI001 Sa20", uom: "20 KG", nameEn: "Sifto - Salt", nameAr: "ملح" },
  { no: "61", category: "Food Ingredients - مواد غذائية", code: "SPI071 Tatri", uom: "5 LB", nameEn: "Citric Acid (Tatri)", nameAr: "سيتريك أسيد" },
  { no: "62", category: "Food Ingredients - مواد غذائية", code: "VIN003 Vin10", uom: "4x4 LT", nameEn: "Lion - Vinegar - White", nameAr: "خل أبيض" },
  { no: "63", category: "Food Ingredients - مواد غذائية", code: "VIN016", uom: "6x4 LT", nameEn: "Reinhart-Allen's - Vinegar Pure Apple Cider", nameAr: "خل مرا" },
  { no: "64", category: "Food Ingredients - مواد غذائية", code: "GUG006", uom: "1", nameEn: "Red Path Sugar - Icing", nameAr: "سكر آيسنج" },
  { no: "65", category: "Food Ingredients - مواد غذائية", code: "PR0114", uom: "1", nameEn: "Fresh Coriander - Cilantro", nameAr: "كزبرة طازجة" },
  { no: "66", category: "Food Ingredients - مواد غذائية", code: "CON347", uom: "18 KG", nameEn: "Tahini Paste - Open Tahini", nameAr: "سطل طحينة" },
  { no: "67", category: "Food Ingredients - مواد غذائية", code: "SPI104", uom: "1", nameEn: "White Pepper", nameAr: "فلفل أبيض" },
  { no: "68", category: "Food Ingredients - مواد غذائية", code: "SPA057", uom: "10 LB", nameEn: "Sesame Seed", nameAr: "سمسم" },
  { no: "70", category: "Food Ingredients - مواد غذائية", code: "", uom: "9x445g", nameEn: "Smoked Paprika", nameAr: "بابريكا مدخنة" },
  { no: "71", category: "Food Ingredients - مواد غذائية", code: "", uom: "9x430g", nameEn: "Spanish Paprika", nameAr: "بابريكا اسبانية" },
  { no: "56", category: "Food Ingredients - مواد غذائية", code: "FLR048-Corn S", uom: "50 LB", nameEn: "Ingredion - Corn Starch - Aeroroot", nameAr: "نشا ذرة" },
  { no: "83", category: "Food Ingredients - مواد غذائية", code: "FLR056", uom: "10 LB", nameEn: "Bread Crumbs", nameAr: "كعك مطحون" },
  { no: "84", category: "Food Ingredients - مواد غذائية", code: "CON174", uom: "16x400g", nameEn: "Frenchs - Yellow Mustard Squeeze", nameAr: "خردل أصفر" },
  { no: "85", category: "Food Ingredients - مواد غذائية", code: "CON371", uom: "4 LT", nameEn: "Worcester Sauce - LEA & PERRINS", nameAr: "صوص ببي للهمبرغر" },
  { no: "36", category: "Food Ingredients - مواد غذائية", code: "CON106", uom: "24x21g", nameEn: "Maggi - Chicken Cubes", nameAr: "ماجي دجاج" },
  { no: "33", category: "Food Ingredients - مواد غذائية", code: "COL008", uom: "20x400g", nameEn: "Preema - Lemon Yellow Colour", nameAr: "صبغة لون أصفر" },
  { no: "34", category: "Food Ingredients - مواد غذائية", code: "COL007", uom: "20x400g", nameEn: "Preema - Food Colour - Orange", nameAr: "صبغة لون برتقالي" },
  { no: "35", category: "Food Ingredients - مواد غذائية", code: "COL002", uom: "20x400g", nameEn: "Preema - Food Colour - Bright Red", nameAr: "صبغة لون أحمر فاتح" },
  { no: "", category: "Food Ingredients - مواد غذائية", code: "GRC139", uom: "2x4 LT", nameEn: "VSO - Strubs - Dill Pickles - Sliced - for Hamburger", nameAr: "خيار رائحة للغر" },
  { no: "51", category: "Food Ingredients - مواد غذائية", code: "PRO146", uom: "5 LB", nameEn: "Fresh - Cole Slaw Mix (Shredded Cabbage)", nameAr: "قرنبيط للكول سلو" },
  { no: "47", category: "Food Ingredients - مواد غذائية", code: "CON004", uom: "20x575ml", nameEn: "Heinz - Ketchup - Upside Down Bottle", nameAr: "علب شبكة" },
  { no: "48", category: "Food Ingredients - مواد غذائية", code: "COP037", uom: "500x9g", nameEn: "Wings - Portions - Hot Chilli Sauce", nameAr: "ظروف صوص هوت" },
  { no: "69", category: "Food Ingredients - مواد غذائية", code: "COP038", uom: "CT", nameEn: "Ketchup Packet", nameAr: "ظروف شبكة" },
  // منتجات الألبان - Dairy & Refrigerated
  { no: "42", category: "Dairy & Refrigerated - منتجات الألبان", code: "DAI054", uom: "5x2 KG", nameEn: "Silani - Cheese - Nacho Shredded - Mozzarella", nameAr: "موزاريلا" },
  { no: "43", category: "Dairy & Refrigerated - منتجات الألبان", code: "DAI039", uom: "2x2.5 KG", nameEn: "Krinos - Cheese - Grated Parmesan Blend", nameAr: "جبنة للازرالي صوص" },
  { no: "44", category: "Dairy & Refrigerated - منتجات الألبان", code: "DAI117-DaiE12", uom: "15x12CT", nameEn: "Burnbrae - Eggs - Large - Loose", nameAr: "بيض" },
  { no: "45", category: "Dairy & Refrigerated - منتجات الألبان", code: "CAN001", uom: "6x1100Z", nameEn: "Cedar - Chick Peas - Large", nameAr: "علب حمص للمسحة" },
  { no: "46", category: "Dairy & Refrigerated - منتجات الألبان", code: "CAN150", uom: "12x141ml", nameEn: "Green Giant - Niblet Corn", nameAr: "ذرة للسلطة" },
  { no: "39", category: "Dairy & Refrigerated - منتجات الألبان", code: "CON012-Con401", uom: "15.4 LT", nameEn: "Chef Nutri - Mayonnaise - Real", nameAr: "مايونيز كبير" },
  { no: "55", category: "Dairy & Refrigerated - منتجات الألبان", code: "DAI179-DAIY109", uom: "24x473ml", nameEn: "Elegant - Yogurt Drink - Ayran", nameAr: "عيران" },
  { no: "57", category: "Dairy & Refrigerated - منتجات الألبان", code: "DAIB02", uom: "BOX", nameEn: "Gay Lea - Unsalted Butter", nameAr: "زبدة غير مملة" },
  { no: "29", category: "Dairy & Refrigerated - منتجات الألبان", code: "DAIO66", uom: "2 KG", nameEn: "Chef Nutri - Cheese - Putin", nameAr: "جبنة بوتين" },
  { no: "", category: "Dairy & Refrigerated - منتجات الألبان", code: "CON110", uom: "4x1.5 KG", nameEn: "Rose Hill - Poutine Quebecoise Mix Base - Gravy", nameAr: "سطل بيبي" },
  { no: "82", category: "Dairy & Refrigerated - منتجات الألبان", code: "CON088", uom: "1.5 KG", nameEn: "Putin Powder - Knorr Culinary Cream Base", nameAr: "بودر البوتين" },
  { no: "87", category: "Dairy & Refrigerated - منتجات الألبان", code: "", uom: "", nameEn: "Cheddar Slices - Cheese", nameAr: "جبنة الهمبرغر" },
  { no: "89", category: "Dairy & Refrigerated - منتجات الألبان", code: "BRD026", uom: "8CT", nameEn: "Wonder - Ballpark - Hamburger Bun Bread", nameAr: "خبز همبرغر" },
  // مواد التنظيف - Cleaning Supplies
  { no: "52", category: "Cleaning Supplies - مواد التنظيف", code: "CHM061", uom: "4x3.78 LT", nameEn: "DAWN - Dishwashing Detergent", nameAr: "سائل الجلي الأزرق" },
  { no: "53", category: "Cleaning Supplies - مواد التنظيف", code: "CHM094-C141G", uom: "4x4 LT", nameEn: "GK - Fryer & Grill Cleaner - Oven Buddy", nameAr: "منظف غريل وفراير" },
  { no: "54", category: "Cleaning Supplies - مواد التنظيف", code: "CHM269", uom: "3.357 LT", nameEn: "Clorox - Germicidal Bleach", nameAr: "كلور" },
  { no: "50", category: "Cleaning Supplies - مواد التنظيف", code: "CHM047", uom: "4x949ml", nameEn: "Lysol - All Purpose Cleaner", nameAr: "لايزول منظف" },
  { no: "81", category: "Cleaning Supplies - مواد التنظيف", code: "", uom: "3x4.24 LT", nameEn: "Pine-sol Cleaner - Lavender Scent", nameAr: "معطر أرض" },
  { no: "31", category: "Cleaning Supplies - مواد التنظيف", code: "NET001", uom: "100CT", nameEn: "Hairnet - Black", nameAr: "هيرنت للشعر" },
  { no: "37", category: "Cleaning Supplies - مواد التنظيف", code: "GBG017-B903", uom: "200CT", nameEn: "Spartano - Garbage Bags - Strong - Black - 26\"x36\"", nameAr: "أكياس زبالة صغيرة" },
  { no: "38", category: "Cleaning Supplies - مواد التنظيف", code: "GBG023-B911", uom: "125CT", nameEn: "Spartano - Garbage Bags - Strong - Black - 42\"x48\"", nameAr: "أكياس زبالة كبيرة" },
  // مشروبات - Beverages
  { no: "72", category: "Beverages - مشروبات", code: "WAT001", uom: "24x500ml", nameEn: "Nestle - Water - Bottles", nameAr: "ماء 24 قنينة" },
  { no: "73", category: "Beverages - مشروبات", code: "POP001-PopCo2401", uom: "24x355ml", nameEn: "Coca Cola - Coke - Original - Cans", nameAr: "كولا" },
  { no: "74", category: "Beverages - مشروبات", code: "POP002-PopCo2403", uom: "24x355ml", nameEn: "Diet Coke - Cans", nameAr: "كولا ديتا" },
  { no: "75", category: "Beverages - مشروبات", code: "POP003-PopCo2402", uom: "24x355ml", nameEn: "Coke Zero - Cans", nameAr: "كولا زيرو" },
  { no: "76", category: "Beverages - مشروبات", code: "POP028-PopCa2401", uom: "24x355ml", nameEn: "Canada Dry - Gingerale - Cans", nameAr: "كولا جينجر" },
  { no: "77", category: "Beverages - مشروبات", code: "POP045-PopSp2401", uom: "24x355ml", nameEn: "Sprite - Cans", nameAr: "كولا سبرايت" },
  { no: "78", category: "Beverages - مشروبات", code: "POP072-PopPe2401", uom: "24x355ml", nameEn: "Pepsi - Diet - Cans", nameAr: "بيبسي ديتا" },
  { no: "79", category: "Beverages - مشروبات", code: "POP074-PopPe2402", uom: "24x355ml", nameEn: "Pepsi - Original - Cans", nameAr: "بيبسي" },
  { no: "80", category: "Beverages - مشروبات", code: "POP089-PopCr2402", uom: "24x355ml", nameEn: "Pepsi - Crush - Orange - Cans", nameAr: "بيبسي كراش" },
]
