export const DEFAULT_ORDER_ITEMS = [
  // أكواب وأطباق
  { category: "أكواب وأطباق", name: "1 - صحون فرايز صغير 6x6x3 BLACK - TOC588" },
  { category: "أكواب وأطباق", name: "2 - صحون حجم عادي 9x6x3 BLACK - TOC338" },
  { category: "أكواب وأطباق", name: "3 - صحون سلطة كبير 9x9x2.8 BLACK - TOC085" },
  { category: "أكواب وأطباق", name: "4 - صحون عروس 9x9x2.8 3Compt BLACK - TOC087" },
  { category: "أكواب وأطباق", name: "15 - أكواب للشوربة 6oz - CUP027" },
  { category: "أكواب وأطباق", name: "16 - كرتونة وجبة الواردة المفردة 4x40" },
  // صحون المشوي
  { category: "صحون المشوي", name: "17 - غطاء صحن المشوي دجاجة واحدة - ALU026" },
  { category: "صحون المشوي", name: "18 - صحن المشوي دجاجة واحدة Half Deep - ALU015" },
  { category: "صحون المشوي", name: "19 - غطاء صحن المشوي فامیلي Full Size" },
  { category: "صحون المشوي", name: "20 - صحن المشوي فامیلي Full Size Medium - ALU005" },
  { category: "صحون المشوي", name: "ALU104 - غطاء صحن المشوي نصف دجاجة Heavy" },
  { category: "صحون المشوي", name: "ALU102 - صحن المشوي نصف دجاجة Medium" },
  // علب الصوص
  { category: "علب الصوص", name: "6 - علب التوم الصغيرة 1 أونص - TOC038" },
  { category: "علب الصوص", name: "7 - غطاء علب التوم الصغيرة 1 أونص - TOC039" },
  { category: "علب الصوص", name: "8 - علب التوم الصغيرة 2 أونص - TOC042" },
  { category: "علب الصوص", name: "9 - غطاء علب التوم الصغيرة 2 أونص - TOC043" },
  { category: "علب الصوص", name: "10 - علب توم الفامیلي 8oz - TOC118" },
  { category: "علب الصوص", name: "11 - غطاء علب توم الفامیلي - TOC124" },
  { category: "علب الصوص", name: "12 - علب صوص المندي 4 أونص - TOC393" },
  { category: "علب الصوص", name: "13 - غطاء علب صوص المندي 4 أونص - TOC806" },
  { category: "علب الصوص", name: "47 - علب شبكة Ketchup Heinz 20x575ml - CON004" },
  { category: "علب الصوص", name: "48 - ظروف صوص هوت Wings 500x9g - COP037" },
  { category: "علب الصوص", name: "69 - ظروف شبكة Ketchup Packet - COP038" },
  // أدوات المائدة
  { category: "أدوات المائدة", name: "5 - معالق مغلفة 1000ct - CUT124" },
  { category: "أدوات المائدة", name: "21 - شوك سودة 1000ct - CUT007" },
  { category: "أدوات المائدة", name: "22 - شلمونات 8 inch 9x400ct - STR049" },
  { category: "أدوات المائدة", name: "23 - ورق لف السندوش 14x14 - WRP011" },
  { category: "أدوات المائدة", name: "24 - ورق 14x14 للصواني - WRP073" },
  { category: "أدوات المائدة", name: "25 - لوينا شفاف 18x2000 - WRP020" },
  { category: "أدوات المائدة", name: "26 - ورق زبدة 14x14 parchment paper" },
  { category: "أدوات المائدة", name: "27 - كرار قصدير للتغليف 18 inch 100M - WRP080" },
  { category: "أدوات المائدة", name: "28 - محارم نابكين 12x500ct - NAP007" },
  { category: "أدوات المائدة", name: "14 - أكياس لوينا كبيرة 1000ct - BAG015" },
  { category: "أدوات المائدة", name: "30 - محارم بيضاء لمسح البسطة 4x6 - PAP118" },
  { category: "أدوات المائدة", name: "32 - ورق طابعة الكاش 50 ROLLS" },
  // مواد غذائية
  { category: "مواد غذائية", name: "40 - بطاطا فرايز Cavendish 3/8 6x4.5lb - FRO158" },
  { category: "مواد غذائية", name: "41 - زيت نقي 16Lt - OIL087" },
  { category: "مواد غذائية", name: "49 - طحين كيس 20KG - FLR006" },
  { category: "مواد غذائية", name: "SUG001 - سكر 10x2kg" },
  { category: "مواد غذائية", name: "58 - توم مقشر طازج 18LB - PR0084" },
  { category: "مواد غذائية", name: "59 - حمص حبة 50lb - LEN079" },
  { category: "مواد غذائية", name: "60 - ملح 20kg - SPI001" },
  { category: "مواد غذائية", name: "61 - سيتريك أسيد 5lb - SPI071" },
  { category: "مواد غذائية", name: "62 - خل أبيض 4x4Lt - VIN003" },
  { category: "مواد غذائية", name: "63 - خل مرا 6x4Lt - VIN016" },
  { category: "مواد غذائية", name: "64 - سكر آيسنج - GUG006" },
  { category: "مواد غذائية", name: "65 - كزبرة طازجة - PR0114" },
  { category: "مواد غذائية", name: "66 - سطل طحينة 18KG - CON347" },
  { category: "مواد غذائية", name: "67 - فلفل أبيض - SPI104" },
  { category: "مواد غذائية", name: "68 - سمسم 10LB - SPA057" },
  { category: "مواد غذائية", name: "70 - بابريكا مدخنة 9x445g Smoked Paprika" },
  { category: "مواد غذائية", name: "71 - بابريكا اسبانية 9x430g Spanish Paprika" },
  { category: "مواد غذائية", name: "56 - نشا ذرة 50lb - FLR048" },
  { category: "مواد غذائية", name: "83 - كعك مطحون Bread Crumbs 10lb - FLR056" },
  { category: "مواد غذائية", name: "84 - خردل أصفر 16x400g - CON174" },
  { category: "مواد غذائية", name: "85 - صوص ببي للهمبرغر Worcester 4Lt - CON371" },
  { category: "مواد غذائية", name: "36 - ماجي دجاج 24x21g - CON106" },
  { category: "مواد غذائية", name: "33 - صبغة لون أصفر 20x400g - COL008" },
  { category: "مواد غذائية", name: "34 - صبغة لون برتقالي 20x400g - COL007" },
  { category: "مواد غذائية", name: "35 - صبغة لون أحمر فاتح 20x400g - COL002" },
  { category: "مواد غذائية", name: "GRC139 - خيار رائحة للغر 2x4Lt" },
  { category: "مواد غذائية", name: "51 - قرنبيط للكول سلو 5lb - PRO146" },
  // منتجات الألبان
  { category: "منتجات الألبان", name: "42 - موزاريلا Silani 5x2kg - DAI054" },
  { category: "منتجات الألبان", name: "43 - جبنة للازرالي صوص Parmesan 2x2.5kg - DAI039" },
  { category: "منتجات الألبان", name: "44 - بيض 15x12ct - DAI117" },
  { category: "منتجات الألبان", name: "45 - علب حمص للمسحة 6x1100Z - CAN001" },
  { category: "منتجات الألبان", name: "46 - ذرة للسلطة 12x141ml - CAN150" },
  { category: "منتجات الألبان", name: "39 - مايونيز كبير 15.4Lt - CON012" },
  { category: "منتجات الألبان", name: "55 - عيران Ayran 24x473ml - DAI179" },
  { category: "منتجات الألبان", name: "57 - زبدة غير مملة Unsalted Butter - DAIB02" },
  { category: "منتجات الألبان", name: "29 - جبنة البوتين 2KG - DAIO66" },
  { category: "منتجات الألبان", name: "CON110 - سطل بيبي Gravy 4x1.5kg" },
  { category: "منتجات الألبان", name: "82 - بودر البوتين Knorr 1.5kg - CON088" },
  { category: "منتجات الألبان", name: "87 - جبنة الهمبرغر Cheddar Slices" },
  { category: "منتجات الألبان", name: "89 - خبز همبرغر 8ct Wonder - BRD026" },
  // مواد التنظيف
  { category: "مواد التنظيف", name: "52 - سائل الجلي الأزرق DAWN 4x3.78Lt - CHM061" },
  { category: "مواد التنظيف", name: "53 - منظف غريل وفراير 4x4Lt - CHM094" },
  { category: "مواد التنظيف", name: "54 - كلور Clorox 3.357Lt - CHM269" },
  { category: "مواد التنظيف", name: "50 - لايزول منظف 4x949ml - CHM047" },
  { category: "مواد التنظيف", name: "81 - معطر أرض Pine-sol 3x4.24Lt" },
  { category: "مواد التنظيف", name: "31 - هيرنت للشعر 100ct - NET001" },
  { category: "مواد التنظيف", name: "37 - أكياس زبالة صغيرة 26x36 200ct - GBG017" },
  { category: "مواد التنظيف", name: "38 - أكياس زبالة كبيرة 42x48 125ct - GBG023" },
  // مشروبات
  { category: "مشروبات", name: "72 - ماء 24 قنينة 500ml - WAT001" },
  { category: "مشروبات", name: "73 - Coca Cola 24x355ml - POP001" },
  { category: "مشروبات", name: "74 - Diet Coke 24x355ml - POP002" },
  { category: "مشروبات", name: "75 - Coke Zero 24x355ml - POP003" },
  { category: "مشروبات", name: "76 - Canada Dry Gingerale 24x355ml - POP028" },
  { category: "مشروبات", name: "77 - Sprite 24x355ml - POP045" },
  { category: "مشروبات", name: "78 - Pepsi Diet 24x355ml - POP072" },
  { category: "مشروبات", name: "79 - Pepsi Original 24x355ml - POP074" },
  { category: "مشروبات", name: "80 - Pepsi Crush Orange 24x355ml - POP089" },
]
